### ISSUE TITLE
Cannot load `y-codemirror`

### ISSUE THREAD

**Issue by aslakhellesoy** [yjs/y-codemirror#6]
To reproduce:

```
node -e "require('y-codemirror')"
```

This results in:

```
internal/modules/cjs/loader.js:326
      throw err;
      ^

Error: Cannot find module '/Users/aslakhellesoy/git/smartbear/examplemapping-frontend/node_modules/y-codemirror/dist/y-codemirror.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:318:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:700:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:131:20)
    at Object.runInThisContext (vm.js:297:38)
    at Object.<anonymous> ([eval]-wrapper:10:26) {
  code: 'MODULE_NOT_FOUND',
  path: 'node_modules/y-codemirror/package.json',
  requestPath: 'y-codemirror'
}
```

This is because `package.json` incorrectly specifies:

```
  "main": "./dist/y-codemirror.js",
```

That file does not exist. This fixes the error:

```
  "main": "./dist/y-codemirror.cjs",
```

**Comment by dmonad** [comment]
Thanks for the report! I'll publish a new release with the correct export in a minute.
